In [1]:
%pip install kagglehub
%pip install numpy 
%pip install pandas
%pip install matplotlib
%pip install seaborn
%pip install scikit-learn

Requirement already satisfied: kagglehub in /Users/mariahwaslie/Desktop/Coding Projects/stats-ML/venv311/lib/python3.11/site-packages (1.0.1)
Requirement already satisfied: kagglesdk<1.0,>=0.1.22 in /Users/mariahwaslie/Desktop/Coding Projects/stats-ML/venv311/lib/python3.11/site-packages (from kagglehub) (0.1.28)
Requirement already satisfied: packaging in /Users/mariahwaslie/Desktop/Coding Projects/stats-ML/venv311/lib/python3.11/site-packages (from kagglehub) (26.0)
Requirement already satisfied: pyyaml in /Users/mariahwaslie/Desktop/Coding Projects/stats-ML/venv311/lib/python3.11/site-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in /Users/mariahwaslie/Desktop/Coding Projects/stats-ML/venv311/lib/python3.11/site-packages (from kagglehub) (2.32.5)
Requirement already satisfied: tqdm in /Users/mariahwaslie/Desktop/Coding Projects/stats-ML/venv311/lib/python3.11/site-packages (from kagglehub) (4.67.3)
Requirement already satisfied: protobuf in /Users/mariahwaslie/Desktop/Coding Projects/stats-ML/venv311/lib/python3.11/site-packages (from kagglesdk<1.0,>=0.1.22->kagglehub) (6.33.6)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/mariahwaslie/Desktop/Coding Projects/stats-ML/venv311/lib/python3.11/site-packages (from requests->kagglehub) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/mariahwaslie/Desktop/Coding Projects/stats-ML/venv311/lib/python3.11/site-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/mariahwaslie/Desktop/Coding Projects/stats-ML/venv311/lib/python3.11/site-packages (from requests->kagglehub) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /Users/mariahwaslie/Desktop/Coding Projects/stats-ML/venv311/lib/python3.11/site-packages (from requests->kagglehub) (2026.2.25)

[notice] A new release of pip is available: 26.0 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: numpy in /Users/mariahwaslie/Desktop/Coding Projects/stats-ML/venv311/lib/python3.11/site-packages (2.4.2)

[notice] A new release of pip is available: 26.0 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: pandas in /Users/mariahwaslie/Desktop/Coding Projects/stats-ML/venv311/lib/python3.11/site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in /Users/mariahwaslie/Desktop/Coding Projects/stats-ML/venv311/lib/python3.11/site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/mariahwaslie/Desktop/Coding Projects/stats-ML/venv311/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/mariahwaslie/Desktop/Coding Projects/stats-ML/venv311/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: matplotlib in /Users/mariahwaslie/Desktop/Coding Projects/stats-ML/venv311/lib/python3.11/site-packages (3.10.9)
Requirement already satisfied: contourpy>=1.0.1 in /Users/mariahwaslie/Desktop/Coding Projects/stats-ML/venv311/lib/python3.11/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Users/mariahwaslie/Desktop/Coding Projects/stats-ML/venv311/lib/python3.11/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/mariahwaslie/Desktop/Coding Projects/stats-ML/venv311/lib/python3.11/site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/mariahwaslie/Desktop/Coding Projects/stats-ML/venv311/lib/python3.11/site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in /Users/mariahwaslie/Desktop/Coding Projects/stats-ML/venv311/lib/python3.11/site-packages (from matplotlib) (2.4.2)
Requirement already satisfied: packaging>=20.0 in /Users/mariahwaslie/Desktop/Coding Projects/stats-ML/venv311/lib/python3.11/site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in /Users/mariahwaslie/Desktop/Coding Projects/stats-ML/venv311/lib/python3.11/site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in /Users/mariahwaslie/Desktop/Coding Projects/stats-ML/venv311/lib/python3.11/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /Users/mariahwaslie/Desktop/Coding Projects/stats-ML/venv311/lib/python3.11/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/mariahwaslie/Desktop/Coding Projects/stats-ML/venv311/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

[notice] A new release of pip is available: 26.0 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: seaborn in /Users/mariahwaslie/Desktop/Coding Projects/stats-ML/venv311/lib/python3.11/site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /Users/mariahwaslie/Desktop/Coding Projects/stats-ML/venv311/lib/python3.11/site-packages (from seaborn) (2.4.2)
Requirement already satisfied: pandas>=1.2 in /Users/mariahwaslie/Desktop/Coding Projects/stats-ML/venv311/lib/python3.11/site-packages (from seaborn) (3.0.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /Users/mariahwaslie/Desktop/Coding Projects/stats-ML/venv311/lib/python3.11/site-packages (from seaborn) (3.10.9)
Requirement already satisfied: contourpy>=1.0.1 in /Users/mariahwaslie/Desktop/Coding Projects/stats-ML/venv311/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Users/mariahwaslie/Desktop/Coding Projects/stats-ML/venv311/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/mariahwaslie/Desktop/Coding Projects/stats-ML/venv311/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/mariahwaslie/Desktop/Coding Projects/stats-ML/venv311/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /Users/mariahwaslie/Desktop/Coding Projects/stats-ML/venv311/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.0)
Requirement already satisfied: pillow>=8 in /Users/mariahwaslie/Desktop/Coding Projects/stats-ML/venv311/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.2.0)
Requirement already satisfied: pyparsing>=3 in /Users/mariahwaslie/Desktop/Coding Projects/stats-ML/venv311/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /Users/mariahwaslie/Desktop/Coding Projects/stats-ML/venv311/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/mariahwaslie/Desktop/Coding Projects/stats-ML/venv311/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

[notice] A new release of pip is available: 26.0 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: scikit-learn in /Users/mariahwaslie/Desktop/Coding Projects/stats-ML/venv311/lib/python3.11/site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in /Users/mariahwaslie/Desktop/Coding Projects/stats-ML/venv311/lib/python3.11/site-packages (from scikit-learn) (2.4.2)
Requirement already satisfied: scipy>=1.10.0 in /Users/mariahwaslie/Desktop/Coding Projects/stats-ML/venv311/lib/python3.11/site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in /Users/mariahwaslie/Desktop/Coding Projects/stats-ML/venv311/lib/python3.11/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /Users/mariahwaslie/Desktop/Coding Projects/stats-ML/venv311/lib/python3.11/site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 26.0 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn as skl

In [3]:
path = pd.read_csv("/Users/mariahwaslie/Desktop/Coding Projects/stats-ML/data/archive/accepted_2007_to_2018q4.csv/accepted_2007_to_2018Q4.csv")
df=path

/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/3490792861.py:1: DtypeWarning: Columns (0: id, 1: desc, 2: next_pymnt_d, 3: verification_status_joint, 4: sec_app_earliest_cr_line, 5: hardship_type, 6: hardship_reason, 7: hardship_status, 8: hardship_start_date, 9: hardship_end_date, 10: payment_plan_start_date, 11: hardship_loan_status, 12: debt_settlement_flag_date, 13: settlement_status, 14: settlement_date) have mixed types. Specify dtype option on import or set low_memory=False.
  path = pd.read_csv("/Users/mariahwaslie/Desktop/Coding Projects/stats-ML/data/archive/accepted_2007_to_2018q4.csv/accepted_2007_to_2018Q4.csv")

In [4]:
df.drop(columns=["id", "member_id","url","desc"], inplace=True)
df.dropna(subset=["term",
                  "grade","sub_grade","home_ownership",
                  "verification_status","purpose"], inplace=True)

In [5]:
df["emp_title"] = df['emp_title'].fillna("Unknown")
print(df["emp_title"])

0                              leadman
1                             Engineer
2                         truck driver
3          Information Systems Officer
4                  Contract Specialist
                      ...
2260694                  Unit Operator
2260695         Database Administrator
2260696                Vice President
2260697                Program Manager
2260698    Customer Service Technician
Name: emp_title, Length: 2260668, dtype: str

In [6]:
df["term"] = df["term"].str.extract(r"(\d+)").astype(int)
print(df["term"])

0          36
1          36
2          60
3          60
4          60
           ..
2260694    60
2260695    60
2260696    60
2260697    60
2260698    60
Name: term, Length: 2260668, dtype: int64

In [7]:
df["emp_length"] = ( df["emp_length"]
                    .str.replace("< 1 year", "0")
                     .str.replace("10+ years", "10")
                     .str.extract(r"(\d+)", expand=False)
                     .astype("Int64")
                      )

print(df["emp_length"].value_counts())

emp_length
10    748005
2     203677
0     189988
3     180753
1     148403
5     139698
4     136605
6     102628
7      92695
8      91914
9      79395
Name: count, dtype: Int64

In [8]:
df.dropna(subset=["issue_d"], inplace=True)
df["issue_d"] = (df["issue_d"]
                 .str.replace(r"Jan", "01")
                 .str.replace(r"Feb", "02")
                 .str.replace(r"Mar", "03")
                 .str.replace(r"Apr", "04")
                 .str.replace(r"May", "05")
                 .str.replace(r"Jun", "06")
                 .str.replace(r"Jul", "07")
                 .str.replace(r"Aug", "08")
                 .str.replace(r"Sep", "09")
                 .str.replace(r"Oct", "10")
                 .str.replace(r"Nov", "11")
                 .str.replace(r"Dec", "12")
                 )
df[["issue_d_month", "issue_d_year"]] = df["issue_d"].str.split("-", expand=True)  

print(df[["issue_d_month", "issue_d_year"]].value_counts())

issue_d_month  issue_d_year
03             2016            61992
10             2015            48631
05             2018            46311
10             2018            46305
08             2018            46079
                               ...
               2007               74
07             2007               63
09             2008               57
               2007               53
06             2007               24
Name: count, Length: 139, dtype: int64

/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/1239799751.py:16: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[["issue_d_month", "issue_d_year"]] = df["issue_d"].str.split("-", expand=True)

In [9]:
df.dropna(subset=["loan_status"], inplace=True)
print(df["loan_status"].value_counts())

loan_status
Fully Paid                                             1076751
Current                                                 878317
Charged Off                                             268559
Late (31-120 days)                                       21467
In Grace Period                                           8436
Late (16-30 days)                                         4349
Does not meet the credit policy. Status:Fully Paid        1988
Does not meet the credit policy. Status:Charged Off        761
Default                                                     40
Name: count, dtype: int64

In [10]:
df["pymnt_plan"] = df["pymnt_plan"].map({"n": 0, "y": 1})
print(df["pymnt_plan"].value_counts())

pymnt_plan
0    2260048
1        620
Name: count, dtype: int64

In [11]:
print(df["zip_code"].value_counts())
df["zip_code"] = (
    df["zip_code"]
    .str.extract(r"(\d+)")
    .fillna(000)
    .astype(int)
)
print(df["zip_code"].value_counts())

zip_code
112xx    23908
945xx    23782
750xx    23649
606xx    21192
300xx    20497
         ...
643xx        1
202xx        1
552xx        1
055xx        1
896xx        1
Name: count, Length: 956, dtype: int64
zip_code
112    23908
945    23782
750    23649
606    21192
300    20497
       ...
643        1
202        1
552        1
55         1
896        1
Name: count, Length: 957, dtype: int64

In [12]:
print(df["addr_state"].value_counts())
df["addr_state"] = df["addr_state"].fillna("NA")

addr_state
CA    314533
NY    186389
TX    186335
FL    161991
IL     91173
NJ     83132
PA     76939
OH     75132
GA     74196
VA     62954
NC     62730
MI     58770
MD     54008
AZ     53777
MA     51784
CO     48183
WA     47060
MN     39517
IN     37515
MO     36084
CT     35785
TN     35483
NV     32657
WI     29877
SC     28003
AL     27284
OR     26789
LA     25759
KY     21887
OK     20691
KS     19109
AR     17074
UT     14993
MS     12639
NM     11986
NH     11142
HI     10668
RI     10005
WV      8351
NE      7819
DE      6458
MT      6299
DC      5356
AK      5231
ME      4974
VT      4937
WY      4748
SD      4549
ID      4308
ND      3591
IA        14
Name: count, dtype: int64

In [13]:
state_coords = {
    'AL': (32.806671, -86.791130),
    'AK': (61.370716, -152.404419),
    'AZ': (33.729759, -111.431221),
    'AR': (34.969704, -92.373123),
    'CA': (36.116203, -119.681564),
    'CO': (39.059811, -105.311104),
    'CT': (41.597782, -72.755371),
    'DE': (39.318523, -75.507141),
    'FL': (27.766279, -81.686783),
    'GA': (33.040619, -83.643074),
    'HI': (21.094318, -157.498337),
    'ID': (44.240459, -114.478828),
    'IL': (40.349457, -88.986137),
    'IN': (39.849426, -86.258278),
    'IA': (42.011539, -93.210526),
    'KS': (38.526600, -96.726486),
    'KY': (37.668140, -84.670067),
    'LA': (31.169546, -91.867805),
    'ME': (44.693947, -69.381927),
    'MD': (39.063946, -76.802101),
    'MA': (42.230171, -71.530106),
    'MI': (43.326618, -84.536095),
    'MN': (45.694454, -93.900192),
    'MS': (32.741646, -89.678696),
    'MO': (38.456085, -92.288368),
    'MT': (46.921925, -110.454353),
    'NE': (41.125370, -98.268082),
    'NV': (38.313515, -117.055374),
    'NH': (43.452492, -71.563896),
    'NJ': (40.298904, -74.521011),
    'NM': (34.840515, -106.248482),
    'NY': (42.165726, -74.948051),
    'NC': (35.630066, -79.806419),
    'ND': (47.528912, -99.784012),
    'OH': (40.388783, -82.764915),
    'OK': (35.565342, -96.928917),
    'OR': (44.572021, -122.070938),
    'PA': (40.590752, -77.209755),
    'RI': (41.680893, -71.511780),
    'SC': (33.856892, -80.945007),
    'SD': (44.299782, -99.438828),
    'TN': (35.747845, -86.692345),
    'TX': (31.054487, -97.563461),
    'UT': (40.150032, -111.862434),
    'VT': (44.045876, -72.710686),
    'VA': (37.769337, -78.169968),
    'WA': (47.400902, -121.490494),
    'WV': (38.491226, -80.954453),
    'WI': (44.268543, -89.616508),
    'WY': (42.755966, -107.302490),
    'DC': (38.9072, -77.0369),
    'NA': (0.0, 0.0)
}

In [14]:
df[['latitude', 'longitude']] = (df['addr_state']
                                 .map(state_coords)
                                 .apply(pd.Series)
                                 )
df = df.drop(columns=['addr_state'])
print(df[['latitude', 'longitude']].value_counts())

latitude   longitude
36.116203  -119.681564    314533
42.165726  -74.948051     186389
31.054487  -97.563461     186335
27.766279  -81.686783     161991
40.349457  -88.986137      91173
40.298904  -74.521011      83132
40.590752  -77.209755      76939
40.388783  -82.764915      75132
33.040619  -83.643074      74196
37.769337  -78.169968      62954
35.630066  -79.806419      62730
43.326618  -84.536095      58770
39.063946  -76.802101      54008
33.729759  -111.431221     53777
42.230171  -71.530106      51784
39.059811  -105.311104     48183
47.400902  -121.490494     47060
45.694454  -93.900192      39517
39.849426  -86.258278      37515
38.456085  -92.288368      36084
41.597782  -72.755371      35785
35.747845  -86.692345      35483
38.313515  -117.055374     32657
44.268543  -89.616508      29877
33.856892  -80.945007      28003
32.806671  -86.791130      27284
44.572021  -122.070938     26789
31.169546  -91.867805      25759
37.668140  -84.670067      21887
35.565342  -96.928917      20691
38.526600  -96.726486      19109
34.969704  -92.373123      17074
40.150032  -111.862434     14993
32.741646  -89.678696      12639
34.840515  -106.248482     11986
43.452492  -71.563896      11142
21.094318  -157.498337     10668
41.680893  -71.511780      10005
38.491226  -80.954453       8351
41.125370  -98.268082       7819
39.318523  -75.507141       6458
46.921925  -110.454353      6299
38.907200  -77.036900       5356
61.370716  -152.404419      5231
44.693947  -69.381927       4974
44.045876  -72.710686       4937
42.755966  -107.302490      4748
44.299782  -99.438828       4549
44.240459  -114.478828      4308
47.528912  -99.784012       3591
42.011539  -93.210526         14
Name: count, dtype: int64

/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/595718255.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[['latitude', 'longitude']] = (df['addr_state']

In [15]:
print(df[['latitude', 'longitude']].info())

<class 'pandas.DataFrame'>
Index: 2260668 entries, 0 to 2260698
Data columns (total 2 columns):
 #   Column     Dtype
---  ------     -----
 0   latitude   float64
 1   longitude  float64
dtypes: float64(2)
memory usage: 51.7 MB
None

In [16]:
df["earliest_cr_line"] = (df["earliest_cr_line"]
                        .str.replace(r"Jan", "01")
                        .str.replace(r"Feb", "02")
                        .str.replace(r"Mar", "03")
                        .str.replace(r"Apr", "04")
                        .str.replace(r"May", "05")
                        .str.replace(r"Jun", "06")
                        .str.replace(r"Jul", "07")
                        .str.replace(r"Aug", "08")
                        .str.replace(r"Sep", "09")
                        .str.replace(r"Oct", "10")
                        .str.replace(r"Nov", "11")
                        .str.replace(r"Dec", "12")
                        )
df[["earliest_cr_month", "earliest_cr_year"]] = df["earliest_cr_line"].str.split("-", expand=True)  

print(df[["earliest_cr_month", "earliest_cr_year"]].value_counts())

/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/1896209733.py:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[["earliest_cr_month", "earliest_cr_year"]] = df["earliest_cr_line"].str.split("-", expand=True)

earliest_cr_month  earliest_cr_year
09                 2004                15400
                   2003                15215
                   2005                14780
08                 2003                14669
                   2004                14413
                                       ...
11                 1955                    1
02                 1957                    1
12                 1951                    1
08                 1941                    1
12                 1946                    1
Name: count, Length: 754, dtype: int64

In [17]:
print(df[["earliest_cr_month", "earliest_cr_year"]].info())
print("\n\nsum of NA rows:")
print(df[["earliest_cr_month", "earliest_cr_year"]].isna().sum())

df.dropna(subset=["earliest_cr_month", "earliest_cr_year"], inplace=True)
df[["earliest_cr_month", "earliest_cr_year"]] = df[["earliest_cr_month", "earliest_cr_year"]].astype(int)  
print(df[["earliest_cr_month", "earliest_cr_year"]].info())

<class 'pandas.DataFrame'>
Index: 2260668 entries, 0 to 2260698
Data columns (total 2 columns):
 #   Column             Dtype
---  ------             -----
 0   earliest_cr_month  str
 1   earliest_cr_year   str
dtypes: str(2)
memory usage: 51.7 MB
None


sum of NA rows:
earliest_cr_month    29
earliest_cr_year     29
dtype: int64
<class 'pandas.DataFrame'>
Index: 2260639 entries, 0 to 2260698
Data columns (total 2 columns):
 #   Column             Dtype
---  ------             -----
 0   earliest_cr_month  int64
 1   earliest_cr_year   int64
dtypes: int64(2)
memory usage: 51.7 MB
None

In [18]:
print(df["initial_list_status"].value_counts())
df.dropna(subset=["initial_list_status"], inplace=True)
df["initial_list_status"] = df["initial_list_status"].map({"f": 0, "w": 1})

initial_list_status
w    1535467
f     725172
Name: count, dtype: int64

In [19]:
print(df["last_pymnt_d"].value_counts())
print(df["last_pymnt_d"].isna().sum())
df["last_pymnt_d"] = (df["last_pymnt_d"].str.replace(r"Jan", "01")
                        .str.replace(r"Feb", "02")
                        .str.replace(r"Mar", "03")
                        .str.replace(r"Apr", "04")
                        .str.replace(r"May", "05")
                        .str.replace(r"Jun", "06")
                        .str.replace(r"Jul", "07")
                        .str.replace(r"Aug", "08")
                        .str.replace(r"Sep", "09")
                        .str.replace(r"Oct", "10")
                        .str.replace(r"Nov", "11")
                        .str.replace(r"Dec", "12")
                        )
df[["last_pymnt_month", "last_pymnt_year"]] = df["last_pymnt_d"].str.split("-", expand=True)

last_pymnt_d
Mar-2019    853003
Feb-2019     97074
Aug-2018     39615
Jan-2019     38483
Mar-2018     38269
             ...
Jun-2008        20
Mar-2008        17
Jan-2008         9
Feb-2008         7
Dec-2007         2
Name: count, Length: 136, dtype: int64
2427

/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/3597359183.py:16: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[["last_pymnt_month", "last_pymnt_year"]] = df["last_pymnt_d"].str.split("-", expand=True)

In [20]:
print(df[["last_pymnt_month", "last_pymnt_year"]].info())
print("\n\nsum of NA rows:")
print(df[["last_pymnt_month", "last_pymnt_year"]].isna().sum())

df['last_pymnt_month'] = df['last_pymnt_month'].fillna(0).astype(int)
df['last_pymnt_year'] = df['last_pymnt_year'].fillna(0).astype(int)
df[["last_pymnt_month", "last_pymnt_year"]].info()

<class 'pandas.DataFrame'>
Index: 2260639 entries, 0 to 2260698
Data columns (total 2 columns):
 #   Column            Dtype
---  ------            -----
 0   last_pymnt_month  str
 1   last_pymnt_year   str
dtypes: str(2)
memory usage: 51.7 MB
None


sum of NA rows:
last_pymnt_month    2427
last_pymnt_year     2427
dtype: int64
<class 'pandas.DataFrame'>
Index: 2260639 entries, 0 to 2260698
Data columns (total 2 columns):
 #   Column            Dtype
---  ------            -----
 0   last_pymnt_month  int64
 1   last_pymnt_year   int64
dtypes: int64(2)
memory usage: 51.7 MB

In [21]:
print(df["next_pymnt_d"].value_counts())
print(df["next_pymnt_d"].isna().sum())
df["next_pymnt_d"] = (df["next_pymnt_d"].str.replace(r"Jan", "01")
                        .str.replace(r"Feb", "02")
                        .str.replace(r"Mar", "03")
                        .str.replace(r"Apr", "04")
                        .str.replace(r"May", "05")
                        .str.replace(r"Jun", "06")
                        .str.replace(r"Jul", "07")
                        .str.replace(r"Aug", "08")
                        .str.replace(r"Sep", "09")
                        .str.replace(r"Oct", "10")
                        .str.replace(r"Nov", "11")
                        .str.replace(r"Dec", "12")
                        )
df[["next_pymnt_month", "next_pymnt_year"]] = df["next_pymnt_d"].str.split("-", expand=True)

next_pymnt_d
Apr-2019    912221
Mar-2019       277
Mar-2011       107
May-2019       105
Apr-2011       101
             ...
Feb-2018         1
Feb-2019         1
Mar-2015         1
May-2008         1
Feb-2008         1
Name: count, Length: 106, dtype: int64
1345310

/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/2501312836.py:16: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[["next_pymnt_month", "next_pymnt_year"]] = df["next_pymnt_d"].str.split("-", expand=True)

In [22]:
df['next_pymnt_month'] = df['next_pymnt_month'].fillna(0).astype(int)
df['next_pymnt_year'] = df['next_pymnt_year'].fillna(0).astype(int)
df[["next_pymnt_month", "next_pymnt_year"]].info()

<class 'pandas.DataFrame'>
Index: 2260639 entries, 0 to 2260698
Data columns (total 2 columns):
 #   Column            Dtype
---  ------            -----
 0   next_pymnt_month  int64
 1   next_pymnt_year   int64
dtypes: int64(2)
memory usage: 51.7 MB

In [23]:
print(df["last_credit_pull_d"].value_counts())
print(df["last_credit_pull_d"].isna().sum())
df["last_credit_pull_d"] = (df["last_credit_pull_d"].str.replace(r"Jan", "01")
                        .str.replace(r"Feb", "02")
                        .str.replace(r"Mar", "03")
                        .str.replace(r"Apr", "04")
                        .str.replace(r"May", "05")
                        .str.replace(r"Jun", "06")
                        .str.replace(r"Jul", "07")
                        .str.replace(r"Aug", "08")
                        .str.replace(r"Sep", "09")
                        .str.replace(r"Oct", "10")
                        .str.replace(r"Nov", "11")
                        .str.replace(r"Dec", "12")
                        )
df[["last_credit_pull_month", "last_credit_pull_year"]] = df["last_credit_pull_d"].str.split("-", expand=True)

df['last_credit_pull_month'] = df['last_credit_pull_month'].fillna(0).astype(int)
df['last_credit_pull_year'] = df['last_credit_pull_year'].fillna(0).astype(int)
df[["last_credit_pull_month", "last_credit_pull_year"]].info()

last_credit_pull_d
Mar-2019    1371378
Feb-2019      76955
Jan-2019      63283
Jul-2018      54113
Oct-2016      50983
             ...
Dec-2007          2
May-2007          2
Jun-2008          1
Jul-2008          1
Jul-2007          1
Name: count, Length: 141, dtype: int64
71

/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/1111236900.py:16: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[["last_credit_pull_month", "last_credit_pull_year"]] = df["last_credit_pull_d"].str.split("-", expand=True)

<class 'pandas.DataFrame'>
Index: 2260639 entries, 0 to 2260698
Data columns (total 2 columns):
 #   Column                  Dtype
---  ------                  -----
 0   last_credit_pull_month  int64
 1   last_credit_pull_year   int64
dtypes: int64(2)
memory usage: 51.7 MB

In [24]:
print(df["application_type"].value_counts())
df.dropna(subset=["application_type"], inplace=True)
df["application_type"] = df["application_type"].map({"Individual": 0, "Joint App": 1})
print(df["application_type"].info())

application_type
Individual    2139929
Joint App      120710
Name: count, dtype: int64
<class 'pandas.Series'>
Index: 2260639 entries, 0 to 2260698
Series name: application_type
Non-Null Count    Dtype
--------------    -----
2260639 non-null  int64
dtypes: int64(1)
memory usage: 34.5 MB
None

In [25]:
df["verification_status_joint"] = df["verification_status_joint"].fillna("Unknown")
print(df["verification_status_joint"].value_counts())

verification_status_joint
Unknown            2144909
Not Verified         57403
Source Verified      34827
Verified             23500
Name: count, dtype: int64

In [26]:
print(df["sec_app_earliest_cr_line"].value_counts())
print(df["sec_app_earliest_cr_line"].isna().sum())
df["sec_app_earliest_cr_line"] = (df["sec_app_earliest_cr_line"].str.replace(r"Jan", "01")
                        .str.replace(r"Feb", "02")
                        .str.replace(r"Mar", "03")
                        .str.replace(r"Apr", "04")
                        .str.replace(r"May", "05")
                        .str.replace(r"Jun", "06")
                        .str.replace(r"Jul", "07")
                        .str.replace(r"Aug", "08")
                        .str.replace(r"Sep", "09")
                        .str.replace(r"Oct", "10")
                        .str.replace(r"Nov", "11")
                        .str.replace(r"Dec", "12")
                        )
df[["sec_app_earliest_cr_line_month", "sec_app_earliest_cr_line_year"]] = df["sec_app_earliest_cr_line"].str.split("-", expand=True)

df['sec_app_earliest_cr_line_month'] = df['sec_app_earliest_cr_line_month'].fillna(00).astype(int)
df['sec_app_earliest_cr_line_year'] = df['sec_app_earliest_cr_line_year'].fillna(0000).astype(int)
df[["sec_app_earliest_cr_line_month", "sec_app_earliest_cr_line_year"]].info()

sec_app_earliest_cr_line
Aug-2006    998
Aug-2005    894
Sep-2006    894
Sep-2005    889
Sep-2004    848
           ...
Sep-1964      1
Sep-1967      1
Jul-1971      1
Jun-1959      1
Sep-1963      1
Name: count, Length: 663, dtype: int64
2152618
<class 'pandas.DataFrame'>
Index: 2260639 entries, 0 to 2260698
Data columns (total 2 columns):
 #   Column                          Dtype
---  ------                          -----
 0   sec_app_earliest_cr_line_month  int64
 1   sec_app_earliest_cr_line_year   int64
dtypes: int64(2)
memory usage: 51.7 MB

/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/1877471801.py:16: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[["sec_app_earliest_cr_line_month", "sec_app_earliest_cr_line_year"]] = df["sec_app_earliest_cr_line"].str.split("-", expand=True)

In [27]:
df.dropna(subset=["hardship_flag"], inplace=True)
df["hardship_flag"] = df["hardship_flag"].map({"N": 0, "Y": 1})
df['hardship_flag'].info()

<class 'pandas.Series'>
Index: 2260639 entries, 0 to 2260698
Series name: hardship_flag
Non-Null Count    Dtype
--------------    -----
2260639 non-null  int64
dtypes: int64(1)
memory usage: 34.5 MB

In [28]:
df["hardship_type"] = df["hardship_type"].fillna("None")
df['hardship_type'].info()

df["hardship_type"] = df["hardship_type"].apply(lambda x: 1 if x == "INTEREST ONLY-3 MONTHS DEFERRAL" else 0)

<class 'pandas.Series'>
Index: 2260639 entries, 0 to 2260698
Series name: hardship_type
Non-Null Count    Dtype
--------------    -----
2260639 non-null  str
dtypes: str(1)
memory usage: 34.5 MB

In [29]:
print(df['hardship_type'].value_counts())

hardship_type
0    2249722
1      10917
Name: count, dtype: int64

In [30]:
df["hardship_reason"] = df["hardship_reason"].fillna("NONE")
print(df['hardship_reason'].info())
print(df["hardship_reason"].value_counts())

<class 'pandas.Series'>
Index: 2260639 entries, 0 to 2260698
Series name: hardship_reason
Non-Null Count    Dtype
--------------    -----
2260639 non-null  str
dtypes: str(1)
memory usage: 34.5 MB
None
hardship_reason
NONE                     2249722
NATURAL_DISASTER            2965
EXCESSIVE_OBLIGATIONS       2155
UNEMPLOYMENT                1923
INCOME_CURTAILMENT          1321
MEDICAL                     1294
REDUCED_HOURS                662
DIVORCE                      225
FAMILY_DEATH                 214
DISABILITY                   158
Name: count, dtype: int64

In [31]:
df["hardship_status"] = df["hardship_status"].fillna("NONE")
print(df['hardship_status'].info())
print(df["hardship_status"].value_counts())

<class 'pandas.Series'>
Index: 2260639 entries, 0 to 2260698
Series name: hardship_status
Non-Null Count    Dtype
--------------    -----
2260639 non-null  str
dtypes: str(1)
memory usage: 34.5 MB
None
hardship_status
NONE         2249722
COMPLETED       7819
BROKEN          2266
ACTIVE           832
Name: count, dtype: int64

In [32]:
print(df["hardship_start_date"])

print(df["hardship_start_date"].value_counts())
print(df["hardship_start_date"].isna().sum())
df["hardship_start_date"] = (df["hardship_start_date"]
                            .str.replace(r"Jan", "01")
                            .str.replace(r"Feb", "02")
                            .str.replace(r"Mar", "03")
                            .str.replace(r"Apr", "04")
                            .str.replace(r"May", "05")
                            .str.replace(r"Jun", "06")
                            .str.replace(r"Jul", "07")
                            .str.replace(r"Aug", "08")
                            .str.replace(r"Sep", "09")
                            .str.replace(r"Oct", "10")
                            .str.replace(r"Nov", "11")
                            .str.replace(r"Dec", "12")
                        )
df[["hardship_start_month", "hardship_start_year"]] = df["hardship_start_date"].str.split("-", expand=True)

df['hardship_start_month'] = df['hardship_start_month'].fillna(00).astype(int)
df['hardship_start_year'] = df['hardship_start_year'].fillna(0000).astype(int)
df[["hardship_start_month", "hardship_start_year"]].info()

0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
          ...
2260694    NaN
2260695    NaN
2260696    NaN
2260697    NaN
2260698    NaN
Name: hardship_start_date, Length: 2260639, dtype: str
hardship_start_date
Sep-2017    2444
Oct-2017    1077
Oct-2018     594
Nov-2017     466
Aug-2018     463
Jan-2019     431
Sep-2018     422
Nov-2018     420
Jun-2017     400
May-2017     373
Aug-2017     360
Dec-2017     359
Jul-2018     359
Jan-2018     348
Dec-2018     339
Mar-2019     304
Feb-2019     297
Jul-2017     271
Jun-2018     260
Feb-2018     242
Mar-2018     238
May-2018     216
Apr-2018     205
Feb-2017      11
Apr-2017       9
Mar-2017       6
Jan-2017       3
Name: count, dtype: int64
2249722
<class 'pandas.DataFrame'>
Index: 2260639 entries, 0 to 2260698
Data columns (total 2 columns):
 #   Column                Dtype
---  ------                -----
 0   hardship_start_month  int64
 1   hardship_start_year   int64
dtypes: int64(2)
memory usage: 51.7 MB

/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/1600273349.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[["hardship_start_month", "hardship_start_year"]] = df["hardship_start_date"].str.split("-", expand=True)

In [33]:
# print(df["hardship_end_date"])
print(df["hardship_end_date"].value_counts())
print(df["hardship_end_date"].isna().sum())
df["hardship_end_date"] = (df["hardship_end_date"]
                            .str.replace(r"Jan", "01")
                            .str.replace(r"Feb", "02")
                            .str.replace(r"Mar", "03")
                            .str.replace(r"Apr", "04")
                            .str.replace(r"May", "05")
                            .str.replace(r"Jun", "06")
                            .str.replace(r"Jul", "07")
                            .str.replace(r"Aug", "08")
                            .str.replace(r"Sep", "09")
                            .str.replace(r"Oct", "10")
                            .str.replace(r"Nov", "11")
                            .str.replace(r"Dec", "12")
                        )
df[["hardship_end_month", "hardship_end_year"]] = df["hardship_end_date"].str.split("-", expand=True)

df['hardship_end_month'] = df['hardship_end_month'].fillna(00).astype(int)
df['hardship_end_year'] = df['hardship_end_year'].fillna(0000).astype(int)
df[["hardship_end_month", "hardship_end_year"]].info()

hardship_end_date
Dec-2017    1756
Nov-2017    1325
Jan-2018     749
Jan-2019     517
Dec-2018     509
Mar-2019     468
Nov-2018     413
Feb-2018     401
Oct-2018     397
Oct-2017     396
Aug-2017     386
Sep-2017     368
Feb-2019     367
Mar-2018     356
Apr-2019     333
Sep-2018     299
Apr-2018     295
May-2019     287
Aug-2018     266
May-2018     253
Jul-2018     212
Jun-2018     210
Jul-2017     174
Jun-2019     104
Jun-2017      50
May-2017      16
Apr-2017       6
Mar-2017       4
Name: count, dtype: int64
2249722
<class 'pandas.DataFrame'>
Index: 2260639 entries, 0 to 2260698
Data columns (total 2 columns):
 #   Column              Dtype
---  ------              -----
 0   hardship_end_month  int64
 1   hardship_end_year   int64
dtypes: int64(2)
memory usage: 51.7 MB

/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/728680356.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[["hardship_end_month", "hardship_end_year"]] = df["hardship_end_date"].str.split("-", expand=True)

In [34]:
# print(df["hardship_end_date"])
print(df["payment_plan_start_date"].value_counts())
print(df["payment_plan_start_date"].isna().sum())
df["payment_plan_start_date"] = (df["payment_plan_start_date"]
                            .str.replace(r"Jan", "01")
                            .str.replace(r"Feb", "02")
                            .str.replace(r"Mar", "03")
                            .str.replace(r"Apr", "04")
                            .str.replace(r"May", "05")
                            .str.replace(r"Jun", "06")
                            .str.replace(r"Jul", "07")
                            .str.replace(r"Aug", "08")
                            .str.replace(r"Sep", "09")
                            .str.replace(r"Oct", "10")
                            .str.replace(r"Nov", "11")
                            .str.replace(r"Dec", "12")
                        )
df[["payment_plan_start_month", "payment_plan_start_year"]] = df["payment_plan_start_date"].str.split("-", expand=True)

df['payment_plan_start_month'] = df['payment_plan_start_month'].fillna(00).astype(int)
df['payment_plan_start_year'] = df['payment_plan_start_year'].fillna(0000).astype(int)
df[["payment_plan_start_month", "payment_plan_start_year"]].info()

payment_plan_start_date
Sep-2017    1715
Oct-2017    1629
Nov-2017     640
Oct-2018     538
Nov-2018     481
Aug-2018     456
Sep-2018     416
Dec-2017     413
Jun-2017     394
Feb-2019     387
Dec-2018     379
Jan-2019     368
Jul-2017     343
Jan-2018     329
Feb-2018     307
Mar-2019     302
Jul-2018     297
Aug-2017     294
Jun-2018     231
Apr-2018     218
Mar-2018     218
May-2017     217
May-2018     216
Apr-2019     104
Mar-2017      11
Feb-2017       9
Apr-2017       5
Name: count, dtype: int64
2249722
<class 'pandas.DataFrame'>
Index: 2260639 entries, 0 to 2260698
Data columns (total 2 columns):
 #   Column                    Dtype
---  ------                    -----
 0   payment_plan_start_month  int64
 1   payment_plan_start_year   int64
dtypes: int64(2)
memory usage: 51.7 MB

/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/2502378870.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[["payment_plan_start_month", "payment_plan_start_year"]] = df["payment_plan_start_date"].str.split("-", expand=True)

In [35]:
df["hardship_loan_status"] = df["hardship_loan_status"].fillna("None")

In [36]:
df.dropna(subset= ["disbursement_method"], inplace=True)
df["disbursement_method"] = df["disbursement_method"].map({"Cash": 0, "DirectPay": 1})
print(df["disbursement_method"].info())

<class 'pandas.Series'>
Index: 2260639 entries, 0 to 2260698
Series name: disbursement_method
Non-Null Count    Dtype
--------------    -----
2260639 non-null  int64
dtypes: int64(1)
memory usage: 34.5 MB
None

In [37]:
df.dropna(subset=["debt_settlement_flag"], inplace=True)
df["debt_settlement_flag"] = df["debt_settlement_flag"].map({"N": 0, "Y": 1})
print(df["debt_settlement_flag"].value_counts())

debt_settlement_flag
0    2226393
1      34246
Name: count, dtype: int64

In [38]:
# print(df["hardship_end_date"])
# print(df["debt_settlement_flag_date"].value_counts())
print(df["debt_settlement_flag_date"].isna().sum())
df["debt_settlement_flag_date"] = (df["debt_settlement_flag_date"]
                            .str.replace(r"Jan", "01")
                            .str.replace(r"Feb", "02")
                            .str.replace(r"Mar", "03")
                            .str.replace(r"Apr", "04")
                            .str.replace(r"May", "05")
                            .str.replace(r"Jun", "06")
                            .str.replace(r"Jul", "07")
                            .str.replace(r"Aug", "08")
                            .str.replace(r"Sep", "09")
                            .str.replace(r"Oct", "10")
                            .str.replace(r"Nov", "11")
                            .str.replace(r"Dec", "12")
                        )
df[["debt_settlement_flag_month", "debt_settlement_flag_year"]] = df["debt_settlement_flag_date"].str.split("-", expand=True)

df['debt_settlement_flag_month'] = df['debt_settlement_flag_month'].fillna(00).astype(int)
df['debt_settlement_flag_year'] = df['debt_settlement_flag_year'].fillna(0000).astype(int)
df[["debt_settlement_flag_month", "debt_settlement_flag_year"]].info()

2226393
<class 'pandas.DataFrame'>
Index: 2260639 entries, 0 to 2260698
Data columns (total 2 columns):
 #   Column                      Dtype
---  ------                      -----
 0   debt_settlement_flag_month  int64
 1   debt_settlement_flag_year   int64
dtypes: int64(2)
memory usage: 51.7 MB

/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/2376121171.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[["debt_settlement_flag_month", "debt_settlement_flag_year"]] = df["debt_settlement_flag_date"].str.split("-", expand=True)

In [39]:
df["settlement_status"] = df["settlement_status"].fillna("UNKNOWN")
print(df["settlement_status"].value_counts())

settlement_status
UNKNOWN     2226393
ACTIVE        14704
COMPLETE      14505
BROKEN         5037
Name: count, dtype: int64

In [40]:
print(df["settlement_date"].isna().sum())
df["settlement_date"] = (df["settlement_date"]
                            .str.replace(r"Jan", "01")
                            .str.replace(r"Feb", "02")
                            .str.replace(r"Mar", "03")
                            .str.replace(r"Apr", "04")
                            .str.replace(r"May", "05")
                            .str.replace(r"Jun", "06")
                            .str.replace(r"Jul", "07")
                            .str.replace(r"Aug", "08")
                            .str.replace(r"Sep", "09")
                            .str.replace(r"Oct", "10")
                            .str.replace(r"Nov", "11")
                            .str.replace(r"Dec", "12")
                        )
df[["settlement_month", "settlement_year"]] = df["settlement_date"].str.split("-", expand=True)

df['settlement_month'] = df['settlement_month'].fillna(00).astype(int)
df['settlement_year'] = df['settlement_year'].fillna(0000).astype(int)
df[["settlement_month", "settlement_year"]].info()

2226393
<class 'pandas.DataFrame'>
Index: 2260639 entries, 0 to 2260698
Data columns (total 2 columns):
 #   Column            Dtype
---  ------            -----
 0   settlement_month  int64
 1   settlement_year   int64
dtypes: int64(2)
memory usage: 51.7 MB

/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/2589171856.py:16: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[["settlement_month", "settlement_year"]] = df["settlement_date"].str.split("-", expand=True)

In [41]:
summary = pd.DataFrame({
    "dtype": df.dtypes,
    "missing_count": df.isna().sum(),
    "missing_pct": df.isna().mean() * 100,
    "n_unique": df.nunique()
}).sort_values("missing_count", ascending=False)

summary

,dtype,missing_count,missing_pct,n_unique
orig_projected_additional_accrued_interest,float64,2251988,99.617321,7487
hardship_payoff_balance_amount,float64,2249722,99.517083,10893
hardship_dpd,float64,2249722,99.517083,34
hardship_length,float64,2249722,99.517083,1
payment_plan_start_date,str,2249722,99.517083,27
...,...,...,...,...
total_pymnt,float64,0,0.000000,1633837
out_prncp_inv,float64,0,0.000000,368481
out_prncp,float64,0,0.000000,356141
initial_list_status,int64,0,0.000000,2
settlement_year,int64,0,0.000000,12

In [42]:
def drop_cols_by_missing(df, threshold=0.5, return_dropped=False, verbose=True):
    """
    Efficiently drop columns exceeding missing value threshold.
    
    Parameters
    ----------
    df : pandas.DataFrame
    threshold : float
        Fraction of missing values (0–1)
    return_dropped : bool
        If True, also returns list of dropped columns
    verbose : bool
        Print summary
    
    Returns
    -------
    DataFrame (and optionally list of dropped columns)
    """
    
    # Compute missing fraction ONCE (fast vectorized op)
    missing_frac = df.isna().mean()

    # Boolean mask (faster than building lists first)
    drop_mask = missing_frac > threshold

    # Select columns to drop
    cols_to_drop = missing_frac.index[drop_mask]
    print(cols_to_drop)

    if verbose:
        print(f"Dropping {len(cols_to_drop)} columns > {threshold:.0%} missing")

    # Drop in one operation (fastest path in pandas)
    df_clean = df.drop(columns=cols_to_drop)

    if return_dropped:
        return df_clean, cols_to_drop.tolist()

    return df_clean

In [43]:
df = drop_cols_by_missing(df,threshold=0.70)

Index(['mths_since_last_record', 'mths_since_last_major_derog',
       'annual_inc_joint', 'dti_joint', 'mths_since_recent_bc_dlq',
       'revol_bal_joint', 'sec_app_fico_range_low', 'sec_app_fico_range_high',
       'sec_app_earliest_cr_line', 'sec_app_inq_last_6mths',
       'sec_app_mort_acc', 'sec_app_open_acc', 'sec_app_revol_util',
       'sec_app_open_act_il', 'sec_app_num_rev_accts',
       'sec_app_chargeoff_within_12_mths',
       'sec_app_collections_12_mths_ex_med',
       'sec_app_mths_since_last_major_derog', 'deferral_term',
       'hardship_amount', 'hardship_start_date', 'hardship_end_date',
       'payment_plan_start_date', 'hardship_length', 'hardship_dpd',
       'orig_projected_additional_accrued_interest',
       'hardship_payoff_balance_amount', 'hardship_last_payment_amount',
       'debt_settlement_flag_date', 'settlement_date', 'settlement_amount',
       'settlement_percentage', 'settlement_term'],
      dtype='str')
Dropping 33 columns > 70% missing

In [44]:
def drop_rows_based_on_column_missing(df, col_missing_threshold=0.05, verbose=True):
    """
    Drop rows based on missingness in feature columns only.
    NEVER uses 'dti' in any cleaning logic.
    """

    # Step 1: compute column missing rates
    col_missing = df.isna().mean()

    # Step 2: select "good columns" BUT EXCLUDE target explicitly
    excluded_cols = ["dti"]
    good_cols = [
        col for col in col_missing.index
        if col_missing[col] <= col_missing_threshold
        and col not in excluded_cols
    ]

    # Step 3: drop rows with NA in ONLY feature columns
    cleaned_df = df.dropna(subset=good_cols)

    if verbose:
        print(f"Using {len(good_cols)} feature columns")
        print(f"Dropped {len(df) - len(cleaned_df)} rows (features only, not dti-aware)")

    return cleaned_df

df = drop_rows_based_on_column_missing(df, col_missing_threshold=0.03)

Using 90 feature columns
Dropped 85894 rows (features only, not dti-aware)

In [45]:
df["revol_delinq_missing"] = (
    df["mths_since_recent_revol_delinq"].isna().astype(int)
)
df["mths_since_recent_revol_delinq"] = (
    df["mths_since_recent_revol_delinq"].fillna(999)
)

/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/1619971459.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["revol_delinq_missing"] = (

In [46]:
df["last_delinq_missing"] = (
    df["mths_since_last_delinq"].isna().astype(int)
)

df["mths_since_last_delinq"] = (
    df["mths_since_last_delinq"].fillna(999)
)

/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/1637177198.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["last_delinq_missing"] = (

In [47]:
df["il_util_missing"] = df["il_util"].isna().astype(int)
df["il_util"] = df["il_util"].fillna(df["il_util"].median())

/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/13743070.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["il_util_missing"] = df["il_util"].isna().astype(int)

In [48]:
df["mths_since_recent_inq_missing"] = df["mths_since_recent_inq"].isna().astype(int)
df["mths_since_recent_inq"] = df["mths_since_recent_inq"].fillna(999)

/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/2716765400.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["mths_since_recent_inq_missing"] = df["mths_since_recent_inq"].isna().astype(int)

In [49]:
df["emp_length_missing"] = df["emp_length"].isna().astype(int)

df["emp_length"] = df["emp_length"].fillna(df["emp_length"].median())

/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/2719875836.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["emp_length_missing"] = df["emp_length"].isna().astype(int)

In [50]:
df["num_tl_120dpd_2m_missing"] = df["num_tl_120dpd_2m"].isna().astype(int)

df["num_tl_120dpd_2m"] = df["num_tl_120dpd_2m"].fillna(0)

/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/2305748113.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["num_tl_120dpd_2m_missing"] = df["num_tl_120dpd_2m"].isna().astype(int)

In [51]:
df["rcnt_il_missing"] = df["mths_since_rcnt_il"].isna().astype(int)

df["mths_since_rcnt_il"] = df["mths_since_rcnt_il"].fillna(999)

/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/2073474715.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["rcnt_il_missing"] = df["mths_since_rcnt_il"].isna().astype(int)

In [52]:
df["old_il_acct_missing"] = df["mo_sin_old_il_acct"].isna().astype(int)

df["mo_sin_old_il_acct"] = df["mo_sin_old_il_acct"].fillna(999)

/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/1650780720.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["old_il_acct_missing"] = df["mo_sin_old_il_acct"].isna().astype(int)

In [53]:
df["title"] = df["title"].fillna("Unknown")
print(df["title"].value_counts())

title
Debt consolidation         1150970
Credit card refinancing     469259
Home improvement            136924
Other                       126993
Major purchase               44626
                            ...
Integrity                        1
Credit cards 2012                1
disneyland                       1
New washer and Dryer             1
Moving and Living                1
Name: count, Length: 41664, dtype: int64

In [54]:
df["bc_util_missing"] = df["bc_util"].isna().astype(int)

df["bc_util"] = df["bc_util"].fillna(df["bc_util"].median())

/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/2540805058.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["bc_util_missing"] = df["bc_util"].isna().astype(int)

In [55]:
df["percent_bc_gt_75_missing"] = df["percent_bc_gt_75"].isna().astype(int)

df["percent_bc_gt_75"] = df["percent_bc_gt_75"].fillna(
    df["percent_bc_gt_75"].median()
)

/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/564320377.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["percent_bc_gt_75_missing"] = df["percent_bc_gt_75"].isna().astype(int)

In [56]:
df["bc_open_to_buy_missing"] = df["bc_open_to_buy"].isna().astype(int)

df["bc_open_to_buy"] = df["bc_open_to_buy"].fillna(
    df["bc_open_to_buy"].median()
)

/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/1662294635.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["bc_open_to_buy_missing"] = df["bc_open_to_buy"].isna().astype(int)

In [57]:
df["mths_since_recent_bc_missing"] = df["mths_since_recent_bc"].isna().astype(int)

df["mths_since_recent_bc"] = df["mths_since_recent_bc"].fillna(999)

/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/99584925.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["mths_since_recent_bc_missing"] = df["mths_since_recent_bc"].isna().astype(int)

In [58]:
df["dti_missing"] = df["dti"].isna().astype(int)

# df["dti"] = df["dti"].fillna(df["dti"].median())

/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/1160233469.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["dti_missing"] = df["dti"].isna().astype(int)

In [59]:
df["revol_util_missing"] = df["revol_util"].isna().astype(int)

df["revol_util"] = df["revol_util"].fillna(df["revol_util"].median())

/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/2859476783.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["revol_util_missing"] = df["revol_util"].isna().astype(int)

In [60]:
df["all_util_missing"] = df["all_util"].isna().astype(int)

df["all_util"] = df["all_util"].fillna(df["all_util"].median())

/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/3920872702.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["all_util_missing"] = df["all_util"].isna().astype(int)

In [61]:
df["open_act_il_missing"] = df["open_act_il"].isna().astype(int)
df["open_act_il"] = df["open_act_il"].fillna(0)

/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/1947326973.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["open_act_il_missing"] = df["open_act_il"].isna().astype(int)

In [62]:
df["open_rv_24m_missing"] = df["open_rv_24m"].isna().astype(int)
df["open_rv_24m"] = df["open_rv_24m"].fillna(0)

/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/3314768011.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["open_rv_24m_missing"] = df["open_rv_24m"].isna().astype(int)

In [63]:
# TYPE 1: counts
cols_type1 = [
    "open_il_24m", "open_il_12m", "open_rv_12m",
    "open_acc_6m", "inq_fi", "inq_last_12m", "total_cu_tl"
]

for col in cols_type1:
    df[col + "_missing"] = df[col].isna().astype(int)
    df[col] = df[col].fillna(0)

# TYPE 2: balances
cols_type2 = ["total_bal_il", "max_bal_bc"]

for col in cols_type2:
    df[col + "_missing"] = df[col].isna().astype(int)
    df[col] = df[col].fillna(df[col].median())

/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/2817856241.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col + "_missing"] = df[col].isna().astype(int)
/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/2817856241.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col + "_missing"] = df[col].isna().astype(int)
/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/2817856241.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col + "_missing"] = df[col].isna().astype(int)
/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/2817856241.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col + "_missing"] = df[col].isna().astype(int)
/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/2817856241.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col + "_missing"] = df[col].isna().astype(int)
/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/2817856241.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col + "_missing"] = df[col].isna().astype(int)
/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/2817856241.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col + "_missing"] = df[col].isna().astype(int)
/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/2817856241.py:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col + "_missing"] = df[col].isna().astype(int)
/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/2817856241.py:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col + "_missing"] = df[col].isna().astype(int)

In [64]:
# -----------------------------
# Time features
# -----------------------------

time_cols = [
    "mo_sin_old_rev_tl_op",
    "mo_sin_rcnt_rev_tl_op",
    "mo_sin_rcnt_tl"
]

for col in time_cols:
    df[f"{col}_missing"] = df[col].isna().astype(int)
    df[col] = df[col].fillna(999)


# -----------------------------
# Count features
# -----------------------------

count_cols = [
    "num_rev_accts",
    "num_op_rev_tl",
    "num_il_tl",
    "num_rev_tl_bal_gt_0",
    "num_tl_op_past_12m",
    "num_tl_90g_dpd_24m",
    "num_tl_30dpd",
    "num_accts_ever_120_pd",
    "num_actv_rev_tl",
    "num_bc_tl",
    "num_actv_bc_tl"
]

for col in count_cols:
    df[f"{col}_missing"] = df[col].isna().astype(int)
    df[col] = df[col].fillna(0)


# -----------------------------
# Money / balance features
# -----------------------------

money_cols = [
    "tot_cur_bal",
    "total_rev_hi_lim",
    "total_il_high_credit_limit",
    "avg_cur_bal",
    "tot_hi_cred_lim",
    "tot_coll_amt"
]

for col in money_cols:
    df[f"{col}_missing"] = df[col].isna().astype(int)
    df[col] = df[col].fillna(df[col].median())


# -----------------------------
# Percentage features
# -----------------------------

pct_cols = [
    "pct_tl_nvr_dlq"
]

for col in pct_cols:
    df[f"{col}_missing"] = df[col].isna().astype(int)
    df[col] = df[col].fillna(df[col].median())


# Verify
print(df[time_cols + count_cols + money_cols + pct_cols].isna().sum().sum())

/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/3294747986.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{col}_missing"] = df[col].isna().astype(int)
/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/3294747986.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{col}_missing"] = df[col].isna().astype(int)
/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/3294747986.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{col}_missing"] = df[col].isna().astype(int)
/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/3294747986.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{col}_missing"] = df[col].isna().astype(int)
/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/3294747986.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{col}_missing"] = df[col].isna().astype(int)
/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/3294747986.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{col}_missing"] = df[col].isna().astype(int)
/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/3294747986.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{col}_missing"] = df[col].isna().astype(int)
/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/3294747986.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{col}_missing"] = df[col].isna().astype(int)
/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/3294747986.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{col}_missing"] = df[col].isna().astype(int)
/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/3294747986.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{col}_missing"] = df[col].isna().astype(int)
/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/3294747986.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{col}_missing"] = df[col].isna().astype(int)
/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/3294747986.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{col}_missing"] = df[col].isna().astype(int)
/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/3294747986.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{col}_missing"] = df[col].isna().astype(int)
/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/3294747986.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{col}_missing"] = df[col].isna().astype(int)
/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/3294747986.py:53: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{col}_missing"] = df[col].isna().astype(int)
/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/3294747986.py:53: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{col}_missing"] = df[col].isna().astype(int)
/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/3294747986.py:53: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{col}_missing"] = df[col].isna().astype(int)
/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/3294747986.py:53: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{col}_missing"] = df[col].isna().astype(int)
/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/3294747986.py:53: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{col}_missing"] = df[col].isna().astype(int)
/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/3294747986.py:53: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{col}_missing"] = df[col].isna().astype(int)
/var/folders/zz/8h6rnwtn2s3759zf_90928740000gn/T/ipykernel_22236/3294747986.py:66: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{col}_missing"] = df[col].isna().astype(int)

0

In [65]:
print(df["last_pymnt_d"].value_counts())
df["next_pymnt_d"]=df["next_pymnt_d"].fillna("00-0000")

last_pymnt_d
03-2019    845429
02-2019     95317
08-2018     39106
03-2018     37717
01-2019     37598
            ...
11-2012       222
10-2012       187
09-2012       117
08-2012        62
07-2012        14
Name: count, Length: 81, dtype: int64

In [66]:
summary = pd.DataFrame({
    "dtype": df.dtypes,
    "missing_count": df.isna().sum(),
    "missing_pct": df.isna().mean() * 100,
    "n_unique": df.nunique()
}).sort_values("missing_count", ascending=False)

summary

                                 dtype  missing_count  missing_pct  n_unique
dti                            float64           1698     0.078078     10836
loan_amnt                      float64              0     0.000000      1561
sec_app_earliest_cr_line_year    int64              0     0.000000        65
earliest_cr_year                 int64              0     0.000000        75
last_pymnt_month                 int64              0     0.000000        12
...                                ...            ...          ...       ...
all_util                       float64              0     0.000000       188
total_rev_hi_lim               float64              0     0.000000     33910
inq_fi                         float64              0     0.000000        33
total_cu_tl                    float64              0     0.000000        61
pct_tl_nvr_dlq_missing           int64              0     0.000000         2

[184 rows x 4 columns]

In [67]:
print(df.head())
print(df.info())

   loan_amnt  funded_amnt  funded_amnt_inv  term  int_rate  installment grade  \
0     3600.0       3600.0           3600.0    36     13.99       123.03     C
1    24700.0      24700.0          24700.0    36     11.99       820.28     C
3    35000.0      35000.0          35000.0    60     14.85       829.90     C
4    10400.0      10400.0          10400.0    60     22.45       289.91     F
5    11950.0      11950.0          11950.0    36     13.44       405.18     C

  sub_grade                    emp_title  emp_length  ...  \
0        C4                      leadman          10  ...
1        C1                     Engineer          10  ...
3        C5  Information Systems Officer          10  ...
4        F1          Contract Specialist           3  ...
5        C3         Veterinary Tecnician           4  ...

  num_actv_rev_tl_missing  num_bc_tl_missing num_actv_bc_tl_missing  \
0                       0                  0                      0
1                       0                  0                      0
3                       0                  0                      0
4                       0                  0                      0
5                       0                  0                      0

  tot_cur_bal_missing total_rev_hi_lim_missing  \
0                   0                        0
1                   0                        0
3                   0                        0
4                   0                        0
5                   0                        0

   total_il_high_credit_limit_missing avg_cur_bal_missing  \
0                                   0                   0
1                                   0                   0
3                                   0                   0
4                                   0                   0
5                                   0                   0

  tot_hi_cred_lim_missing  tot_coll_amt_missing  pct_tl_nvr_dlq_missing
0                       0                     0                       0
1                       0                     0                       0
3                       0                     0                       0
4                       0                     0                       0
5                       0                     0                       0

[5 rows x 184 columns]
<class 'pandas.DataFrame'>
Index: 2174745 entries, 0 to 2260697
Columns: 184 entries, loan_amnt to pct_tl_nvr_dlq_missing
dtypes: Int64(1), float64(87), int64(76), str(20)
memory usage: 3.0 GB
None

In [68]:
pd.set_option('display.max_rows', None)    # Show all rows
pd.set_option('display.max_columns', None)
print(path.info())

<class 'pandas.DataFrame'>
Index: 2260668 entries, 0 to 2260698
Columns: 151 entries, loan_amnt to longitude
dtypes: Int64(1), float64(114), int64(3), str(33)
memory usage: 2.6 GB
None

In [69]:
print(path.describe())
print(path.columns)

          loan_amnt   funded_amnt  funded_amnt_inv          term  \
count  2.260668e+06  2.260668e+06     2.260668e+06  2.260668e+06
mean   1.504693e+04  1.504166e+04     1.502344e+04  4.291032e+01
std    9.190245e+03  9.188413e+03     9.192332e+03  1.086716e+01
min    5.000000e+02  5.000000e+02     0.000000e+00  3.600000e+01
25%    8.000000e+03  8.000000e+03     8.000000e+03  3.600000e+01
50%    1.290000e+04  1.287500e+04     1.280000e+04  3.600000e+01
75%    2.000000e+04  2.000000e+04     2.000000e+04  6.000000e+01
max    4.000000e+04  4.000000e+04     4.000000e+04  6.000000e+01

           int_rate   installment  emp_length    annual_inc    pymnt_plan  \
count  2.260668e+06  2.260668e+06   2113761.0  2.260664e+06  2.260668e+06
mean   1.309283e+01  4.458068e+02    5.931359  7.799243e+04  2.742552e-04
std    4.832138e+00  2.671735e+02    3.720212  1.126962e+05  1.655839e-02
min    5.310000e+00  4.930000e+00         0.0  0.000000e+00  0.000000e+00
25%    9.490000e+00  2.516500e+02         2.0  4.600000e+04  0.000000e+00
50%    1.262000e+01  3.779900e+02         6.0  6.500000e+04  0.000000e+00
75%    1.599000e+01  5.933200e+02        10.0  9.300000e+04  0.000000e+00
max    3.099000e+01  1.719830e+03        10.0  1.100000e+08  1.000000e+00

           zip_code           dti   delinq_2yrs  fico_range_low  \
count  2.260668e+06  2.258957e+06  2.260639e+06    2.260668e+06
mean   5.094371e+02  1.882420e+01  3.068792e-01    6.985882e+02
std    3.110757e+02  1.418333e+01  8.672303e-01    3.301038e+01
min    0.000000e+00 -1.000000e+00  0.000000e+00    6.100000e+02
25%    2.300000e+02  1.189000e+01  0.000000e+00    6.750000e+02
50%    4.710000e+02  1.784000e+01  0.000000e+00    6.900000e+02
75%    8.010000e+02  2.449000e+01  0.000000e+00    7.150000e+02
max    9.990000e+02  9.990000e+02  5.800000e+01    8.450000e+02

       fico_range_high  inq_last_6mths  mths_since_last_delinq  \
count     2.260668e+06    2.260638e+06            1.102166e+06
mean      7.025884e+02    5.768354e-01            3.454092e+01
std       3.301124e+01    8.859632e-01            2.190047e+01
min       6.140000e+02    0.000000e+00            0.000000e+00
25%       6.790000e+02    0.000000e+00            1.600000e+01
50%       6.940000e+02    0.000000e+00            3.100000e+01
75%       7.190000e+02    1.000000e+00            5.000000e+01
max       8.500000e+02    3.300000e+01            2.260000e+02

       mths_since_last_record      open_acc       pub_rec     revol_bal  \
count           359156.000000  2.260639e+06  2.260639e+06  2.260668e+06
mean                72.312842  1.161240e+01  1.975278e-01  1.665846e+04
std                 26.464094  5.640861e+00  5.705150e-01  2.294831e+04
min                  0.000000  0.000000e+00  0.000000e+00  0.000000e+00
25%                 55.000000  8.000000e+00  0.000000e+00  5.950000e+03
50%                 74.000000  1.100000e+01  0.000000e+00  1.132400e+04
75%                 92.000000  1.400000e+01  0.000000e+00  2.024600e+04
max                129.000000  1.010000e+02  8.600000e+01  2.904836e+06

         revol_util     total_acc     out_prncp  out_prncp_inv   total_pymnt  \
count  2.258866e+06  2.260639e+06  2.260668e+06   2.260668e+06  2.260668e+06
mean   5.033770e+01  2.416255e+01  4.206891e+03   4.205965e+03  1.208256e+04
std    2.471307e+01  1.198753e+01  7.343239e+03   7.342333e+03  9.901383e+03
min    0.000000e+00  1.000000e+00  0.000000e+00   0.000000e+00  0.000000e+00
25%    3.150000e+01  1.500000e+01  0.000000e+00   0.000000e+00  4.546458e+03
50%    5.030000e+01  2.200000e+01  0.000000e+00   0.000000e+00  9.329720e+03
75%    6.940000e+01  3.100000e+01  6.149940e+03   6.146310e+03  1.694087e+04
max    8.923000e+02  1.760000e+02  4.000000e+04   4.000000e+04  6.329688e+04

       total_pymnt_inv  total_rec_prncp  total_rec_int  total_rec_late_fee  \
count     2.260668e+06     2.260668e+06   2.260668e+06        2.260668e+06
mean      1.206439e+04     9.505772e+03   2.431388e+03        1.518453e+00
std       9.896992e+03     8.321852e+03   2.679738e+03        1.184159e+01
min       0.000000e+00     0.000000e+00   0.000000e+00       -9.500000e-09
25%       4.531800e+03     3.000000e+03   7.281875e+02        0.000000e+00
50%       9.309675e+03     7.000000e+03   1.525940e+03        0.000000e+00
75%       1.691671e+04     1.389910e+04   3.108062e+03        0.000000e+00
max       6.329688e+04     4.000000e+04   2.819250e+04        1.484340e+03

         recoveries  collection_recovery_fee  last_pymnt_amnt  \
count  2.260668e+06             2.260668e+06     2.260668e+06
mean   1.438791e+02             2.398257e+01     3.429346e+03
std    7.481640e+02             1.312256e+02     6.018248e+03
min    0.000000e+00             0.000000e+00     0.000000e+00
25%    0.000000e+00             0.000000e+00     3.103300e+02
50%    0.000000e+00             0.000000e+00     6.005700e+02
75%    0.000000e+00             0.000000e+00     3.743750e+03
max    3.985955e+04             7.174719e+03     4.219205e+04

       last_fico_range_high  last_fico_range_low  collections_12_mths_ex_med  \
count          2.260668e+06         2.260668e+06                2.260523e+06
mean           6.876610e+02         6.755397e+02                1.814580e-02
std            7.297044e+01         1.110976e+02                1.508131e-01
min            0.000000e+00         0.000000e+00                0.000000e+00
25%            6.540000e+02         6.500000e+02                0.000000e+00
50%            6.990000e+02         6.950000e+02                0.000000e+00
75%            7.340000e+02         7.300000e+02                0.000000e+00
max            8.500000e+02         8.450000e+02                2.000000e+01

       mths_since_last_major_derog  policy_code  annual_inc_joint  \
count                580775.000000    2260668.0      1.207100e+05
mean                     44.164220          1.0      1.236246e+05
std                      21.533121          0.0      7.416135e+04
min                       0.000000          1.0      5.693510e+03
25%                      27.000000          1.0      8.340000e+04
50%                      44.000000          1.0      1.100000e+05
75%                      62.000000          1.0      1.479950e+05
max                     226.000000          1.0      7.874821e+06

           dti_joint  acc_now_delinq  tot_coll_amt   tot_cur_bal  \
count  120706.000000    2.260639e+06  2.190392e+06  2.190392e+06
mean       19.251817    4.147942e-03  2.327317e+02  1.424922e+05
std         7.822086    6.961656e-02  8.518462e+03  1.606926e+05
min         0.000000    0.000000e+00  0.000000e+00  0.000000e+00
25%        13.530000    0.000000e+00  0.000000e+00  2.909200e+04
50%        18.840000    0.000000e+00  0.000000e+00  7.924000e+04
75%        24.620000    0.000000e+00  0.000000e+00  2.132040e+05
max        69.490000    1.400000e+01  9.152545e+06  9.971659e+06

        open_acc_6m   open_act_il   open_il_12m   open_il_24m  \
count  1.394538e+06  1.394539e+06  1.394539e+06  1.394539e+06
mean   9.344199e-01  2.779407e+00  6.764314e-01  1.562752e+00
std    1.140700e+00  3.000784e+00  9.256354e-01  1.578672e+00
min    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
25%    0.000000e+00  1.000000e+00  0.000000e+00  0.000000e+00
50%    1.000000e+00  2.000000e+00  0.000000e+00  1.000000e+00
75%    1.000000e+00  3.000000e+00  1.000000e+00  2.000000e+00
max    1.800000e+01  5.700000e+01  2.500000e+01  5.100000e+01

       mths_since_rcnt_il  total_bal_il       il_util   open_rv_12m  \
count        1.350744e+06  1.394539e+06  1.191818e+06  1.394539e+06
mean         2.122236e+01  3.550665e+04  6.914098e+01  1.290133e+00
std          2.604919e+01  4.409746e+04  2.374839e+01  1.506827e+00
min          0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
25%          7.000000e+00  8.695000e+03  5.500000e+01  0.000000e+00
50%          1.300000e+01  2.312700e+04  7.200000e+01  1.000000e+00
75%          2.400000e+01  4.609500e+04  8.600000e+01  2.000000e+00
max          5.110000e+02  1.837038e+06  1.000000e+03  2.800000e+01

        open_rv_24m    max_bal_bc      all_util  total_rev_hi_lim  \
count  1.394539e+06  1.394539e+06  1.394320e+06      2.190392e+06
mean   2.749923e+00  5.806393e+03  5.703230e+01      3.457394e+04
std    2.596911e+00  5.690561e+03  2.090475e+01      3.672850e+04
min    0.000000e+00  0.000000e+00  0.000000e+00      0.000000e+00
25%    1.000000e+00  2.284000e+03  4.300000e+01      1.470000e+04
50%    2.000000e+00  4.413000e+03  5.800000e+01      2.540000e+04
75%    4.000000e+00  7.598000e+03  7.200000e+01      4.320000e+04
max    6.000000e+01  1.170668e+06  2.390000e+02      9.999999e+06

             inq_fi   total_cu_tl  inq_last_12m  acc_open_past_24mths  \
count  1.394539e+06  1.394538e+06  1.394538e+06          2.210638e+06
mean   1.012867e+00  1.477304e+00  2.036667e+00          4.521656e+00
std    1.489456e+00  2.672991e+00  2.383117e+00          3.164229e+00
min    0.000000e+00  0.000000e+00  0.000000e+00          0.000000e+00
25%    0.000000e+00  0.000000e+00  0.000000e+00          2.000000e+00
50%    1.000000e+00  0.000000e+00  1.000000e+00          4.000000e+00
75%    1.000000e+00  2.000000e+00  3.000000e+00          6.000000e+00
max    4.800000e+01  1.110000e+02  6.700000e+01          6.400000e+01

        avg_cur_bal  bc_open_to_buy       bc_util  chargeoff_within_12_mths  \
count  2.190322e+06    2.185733e+06  2.184597e+06              2.260523e+06
mean   1.354780e+04    1.139426e+04  5.789995e+01              8.464413e-03
std    1.647408e+04    1.659953e+04  2.858347e+01              1.048098e-01
min    0.000000e+00    0.000000e+00  0.000000e+00              0.000000e+00
25%    3.080000e+03    1.722000e+03  3.540000e+01              0.000000e+00
50%    7.335000e+03    5.442000e+03  6.020000e+01              0.000000e+00
75%    1.878300e+04    1.418700e+04  8.310000e+01              0.000000e+00
max    9.580840e+05    7.111400e+05  3.396000e+02              1.000000e+01

        delinq_amnt  mo_sin_old_il_acct  mo_sin_old_rev_tl_op  \
count  2.260639e+06        2.121597e+06          2.190391e+06
mean   1.236983e+01        1.257378e+02          1.814916e+02
std    7.264648e+02        5.338218e+01          9.711845e+01
min    0.000000e+00        0.000000e+00          1.000000e+00
25%    0.000000e+00        9.600000e+01          1.160000e+02
50%    0.000000e+00        1.300000e+02          1.640000e+02
75%    0.000000e+00        1.540000e+02          2.320000e+02
max    2.499250e+05        9.990000e+02          9.990000e+02

       mo_sin_rcnt_rev_tl_op  mo_sin_rcnt_tl      mort_acc  \
count           2.190391e+06    2.190392e+06  2.210638e+06
mean            1.402409e+01    8.297469e+00  1.555382e+00
std             1.753308e+01    9.208557e+00  1.904981e+00
min             0.000000e+00    0.000000e+00  0.000000e+00
25%             4.000000e+00    3.000000e+00  0.000000e+00
50%             8.000000e+00    6.000000e+00  1.000000e+00
75%             1.700000e+01    1.100000e+01  3.000000e+00
max             5.470000e+02    3.820000e+02  9.400000e+01

       mths_since_recent_bc  mths_since_recent_bc_dlq  mths_since_recent_inq  \
count          2.187256e+06             519701.000000           1.965233e+06
mean           2.484485e+01                 39.303090           7.024194e+00
std            3.231925e+01                 22.617689           5.965411e+00
min            0.000000e+00                  0.000000           0.000000e+00
25%            6.000000e+00                 21.000000           2.000000e+00
50%            1.400000e+01                 37.000000           5.000000e+00
75%            3.000000e+01                 57.000000           1.100000e+01
max            6.610000e+02                202.000000           2.500000e+01

       mths_since_recent_revol_delinq  num_accts_ever_120_pd  num_actv_bc_tl  \
count                   740359.000000           2.190392e+06    2.190392e+06
mean                        35.782223           5.002082e-01    3.676069e+00
std                         22.307239           1.350326e+00    2.324646e+00
min                          0.000000           0.000000e+00    0.000000e+00
25%                         17.000000           0.000000e+00    2.000000e+00
50%                         33.000000           0.000000e+00    3.000000e+00
75%                         51.000000           0.000000e+00    5.000000e+00
max                        202.000000           5.800000e+01    5.000000e+01

       num_actv_rev_tl   num_bc_sats     num_bc_tl     num_il_tl  \
count     2.190392e+06  2.202078e+06  2.190392e+06  2.190392e+06
mean      5.629468e+00  4.774183e+00  7.726402e+00  8.413439e+00
std       3.382874e+00  3.037921e+00  4.701430e+00  7.359114e+00
min       0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
25%       3.000000e+00  3.000000e+00  4.000000e+00  3.000000e+00
50%       5.000000e+00  4.000000e+00  7.000000e+00  6.000000e+00
75%       7.000000e+00  6.000000e+00  1.000000e+01  1.100000e+01
max       7.200000e+01  7.100000e+01  8.600000e+01  1.590000e+02

       num_op_rev_tl  num_rev_accts  num_rev_tl_bal_gt_0      num_sats  \
count   2.190392e+06   2.190391e+06         2.190392e+06  2.202078e+06
mean    8.246523e+00   1.400463e+01         5.577951e+00  1.162813e+01
std     4.683928e+00   8.038868e+00         3.293434e+00  5.644027e+00
min     0.000000e+00   0.000000e+00         0.000000e+00  0.000000e+00
25%     5.000000e+00   8.000000e+00         3.000000e+00  8.000000e+00
50%     7.000000e+00   1.200000e+01         5.000000e+00  1.100000e+01
75%     1.000000e+01   1.800000e+01         7.000000e+00  1.400000e+01
max     9.100000e+01   1.510000e+02         6.500000e+01  1.010000e+02

       num_tl_120dpd_2m  num_tl_30dpd  num_tl_90g_dpd_24m  num_tl_op_past_12m  \
count      2.107011e+06  2.190392e+06        2.190392e+06        2.190392e+06
mean       6.373958e-04  2.813652e-03        8.293767e-02        2.076755e+00
std        2.710643e-02  5.616522e-02        4.935732e-01        1.830711e+00
min        0.000000e+00  0.000000e+00        0.000000e+00        0.000000e+00
25%        0.000000e+00  0.000000e+00        0.000000e+00        1.000000e+00
50%        0.000000e+00  0.000000e+00        0.000000e+00        2.000000e+00
75%        0.000000e+00  0.000000e+00        0.000000e+00        3.000000e+00
max        7.000000e+00  4.000000e+00        5.800000e+01        3.200000e+01

       pct_tl_nvr_dlq  percent_bc_gt_75  pub_rec_bankruptcies     tax_liens  \
count    2.190237e+06      2.185289e+06          2.259303e+06  2.260563e+06
mean     9.411458e+01      4.243513e+01          1.281935e-01  4.677109e-02
std      9.036140e+00      3.621616e+01          3.646130e-01  3.775338e-01
min      0.000000e+00      0.000000e+00          0.000000e+00  0.000000e+00
25%      9.130000e+01      0.000000e+00          0.000000e+00  0.000000e+00
50%      1.000000e+02      3.750000e+01          0.000000e+00  0.000000e+00
75%      1.000000e+02      7.140000e+01          0.000000e+00  0.000000e+00
max      1.000000e+02      1.000000e+02          1.200000e+01  8.500000e+01

       tot_hi_cred_lim  total_bal_ex_mort  total_bc_limit  \
count     2.190392e+06       2.210638e+06    2.210638e+06
mean      1.782428e+05       5.102294e+04    2.319377e+04
std       1.815748e+05       4.991124e+04    2.300656e+04
min       0.000000e+00       0.000000e+00    0.000000e+00
25%       5.073100e+04       2.089200e+04    8.300000e+03
50%       1.142985e+05       3.786400e+04    1.630000e+04
75%       2.577550e+05       6.435000e+04    3.030000e+04
max       9.999999e+06       3.408095e+06    1.569000e+06

       total_il_high_credit_limit  revol_bal_joint  sec_app_fico_range_low  \
count                2.190392e+06     1.080200e+05           108021.000000
mean                 4.373201e+04     3.361728e+04              669.755603
std                  4.507298e+04     2.815387e+04               44.729163
min                  0.000000e+00     0.000000e+00              540.000000
25%                  1.500000e+04     1.510675e+04              645.000000
50%                  3.269600e+04     2.651650e+04              670.000000
75%                  5.880425e+04     4.376900e+04              695.000000
max                  2.118996e+06     1.110019e+06              845.000000

       sec_app_fico_range_high  sec_app_inq_last_6mths  sec_app_mort_acc  \
count            108021.000000           108021.000000     108021.000000
mean                673.755631                0.633256          1.538997
std                  44.729272                0.993401          1.760569
min                 544.000000                0.000000          0.000000
25%                 649.000000                0.000000          0.000000
50%                 674.000000                0.000000          1.000000
75%                 699.000000                1.000000          2.000000
max                 850.000000                6.000000         27.000000

       sec_app_open_acc  sec_app_revol_util  sec_app_open_act_il  \
count     108021.000000       106184.000000        108021.000000
mean          11.469455           58.169101             3.010554
std            6.627271           25.548212             3.275893
min            0.000000            0.000000             0.000000
25%            7.000000           39.800000             1.000000
50%           10.000000           60.200000             2.000000
75%           15.000000           78.600000             4.000000
max           82.000000          434.300000            43.000000

       sec_app_num_rev_accts  sec_app_chargeoff_within_12_mths  \
count          108021.000000                     108021.000000
mean               12.533072                          0.046352
std                 8.150964                          0.411496
min                 0.000000                          0.000000
25%                 7.000000                          0.000000
50%                11.000000                          0.000000
75%                17.000000                          0.000000
max               106.000000                         21.000000

       sec_app_collections_12_mths_ex_med  \
count                       108021.000000
mean                             0.077568
std                              0.407996
min                              0.000000
25%                              0.000000
50%                              0.000000
75%                              0.000000
max                             23.000000

       sec_app_mths_since_last_major_derog  deferral_term  hardship_amount  \
count                         35942.000000        10917.0     10917.000000
mean                             36.937928            3.0       155.045981
std                              23.924584            0.0       129.040594
min                               0.000000            3.0         0.640000
25%                              16.000000            3.0        59.440000
50%                              36.000000            3.0       119.140000
75%                              56.000000            3.0       213.260000
max                             185.000000            3.0       943.940000

       hardship_length  hardship_dpd  \
count          10917.0  10917.000000
mean               3.0     13.743886
std                0.0      9.671178
min                3.0      0.000000
25%                3.0      5.000000
50%                3.0     15.000000
75%                3.0     22.000000
max                3.0     37.000000

       orig_projected_additional_accrued_interest  \
count                                 8651.000000
mean                                   454.798089
std                                    375.385500
min                                      1.920000
25%                                    175.230000
50%                                    352.770000
75%                                    620.175000
max                                   2680.890000


In [70]:
# Keep only completed loans
df_model = df[
    df["loan_status"].isin([
        "Fully Paid",
        "Charged Off"
    ])
].copy()

In [71]:
df_model["default"] = (
    df_model["loan_status"] == "Charged Off"
).astype(int)

In [72]:
df_model["loan_status"].value_counts()

loan_status
Fully Paid     1016696
Charged Off     253126
Name: count, dtype: int64

In [73]:
df_model.to_csv("../data/lendingclub_model.csv", index=False)